name: Inferno TDD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:  
        include:
          - os: ubuntu-latest
            qt_arch: gcc_64
          - os: macos-latest
            qt_arch: clang_64
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install ninja cmake qt

    - name: Install Dependencies (Linux/WSL)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake libgl1-mesa-dev qt6-base-dev qt6-base-private-dev

    - name: Configure CMake
      run: cmake -B build -S . -G Ninja
      
    - name: Native Build
      run: ninja -C build
      
    - name: Execute Native Assertions
      env:
        INFERNO_TESTING: 1
      run: ./build/inferno_tests
